/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as OrderTokenRouteImport } from './routes/order.$token'
import { Route as PrintBookingBookingIdRouteImport } from './routes/print-booking.$bookingId'
import { Route as PrintBillIdRouteImport } from './routes/print.$billId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTokenRoute = OrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintBookingBookingIdRoute = PrintBookingBookingIdRouteImport.update({
  id: '/print-booking/$bookingId',
  path: '/print-booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintBillIdRoute = PrintBillIdRouteImport.update({
  id: '/print/$billId',
  path: '/print/$billId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/waitlist': typeof WaitlistRoute
  '/order/$token': typeof OrderTokenRoute
  '/print-booking/$bookingId': typeof PrintBookingBookingIdRoute
  '/print/$billId': typeof PrintBillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/waitlist': typeof WaitlistRoute
  '/order/$token': typeof OrderTokenRoute
  '/print-booking/$bookingId': typeof PrintBookingBookingIdRoute
  '/print/$billId': typeof PrintBillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/waitlist': typeof WaitlistRoute
  '/order/$token': typeof OrderTokenRoute
  '/print-booking/$bookingId': typeof PrintBookingBookingIdRoute
  '/print/$billId': typeof PrintBillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/bookings'
    | '/clients'
    | '/dashboard'
    | '/employees'
    | '/menu'
    | '/orders'
    | '/rooms'
    | '/settings'
    | '/tables'
    | '/waitlist'
    | '/order/$token'
    | '/print-booking/$bookingId'
    | '/print/$billId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/bookings'
    | '/clients'
    | '/dashboard'
    | '/employees'
    | '/menu'
    | '/orders'
    | '/rooms'
    | '/settings'
    | '/tables'
    | '/waitlist'
    | '/order/$token'
    | '/print-booking/$bookingId'
    | '/print/$billId'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/bookings'
    | '/clients'
    | '/dashboard'
    | '/employees'
    | '/menu'
    | '/orders'
    | '/rooms'
    | '/settings'
    | '/tables'
    | '/waitlist'
    | '/order/$token'
    | '/print-booking/$bookingId'
    | '/print/$billId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  BookingsRoute: typeof BookingsRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  TablesRoute: typeof TablesRoute
  WaitlistRoute: typeof WaitlistRoute
  OrderTokenRoute: typeof OrderTokenRoute
  PrintBookingBookingIdRoute: typeof PrintBookingBookingIdRoute
  PrintBillIdRoute: typeof PrintBillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$token': {
      id: '/order/$token'
      path: '/order/$token'
      fullPath: '/order/$token'
      preLoaderRoute: typeof OrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-booking/$bookingId': {
      id: '/print-booking/$bookingId'
      path: '/print-booking/$bookingId'
      fullPath: '/print-booking/$bookingId'
      preLoaderRoute: typeof PrintBookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$billId': {
      id: '/print/$billId'
      path: '/print/$billId'
      fullPath: '/print/$billId'
      preLoaderRoute: typeof PrintBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  BookingsRoute: BookingsRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  TablesRoute: TablesRoute,
  WaitlistRoute: WaitlistRoute,
  OrderTokenRoute: OrderTokenRoute,
  PrintBookingBookingIdRoute: PrintBookingBookingIdRoute,
  PrintBillIdRoute: PrintBillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
